/********************************************************************
* src//RootParallelGuiCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src//RootParallelGuiCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevRootParallelGuiCint();
extern G__DLLEXPORT void G__set_cpp_environmentRootParallelGuiCint();
extern G__DLLEXPORT void G__cpp_setup_tagtableRootParallelGuiCint();
extern G__DLLEXPORT void G__cpp_setup_inheritanceRootParallelGuiCint();
extern G__DLLEXPORT void G__cpp_setup_typetableRootParallelGuiCint();
extern G__DLLEXPORT void G__cpp_setup_memvarRootParallelGuiCint();
extern G__DLLEXPORT void G__cpp_setup_globalRootParallelGuiCint();
extern G__DLLEXPORT void G__cpp_setup_memfuncRootParallelGuiCint();
extern G__DLLEXPORT void G__cpp_setup_funcRootParallelGuiCint();
extern G__DLLEXPORT void G__cpp_setupRootParallelGuiCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/RootParallelGui.h"
#include "include/RootParallelGuiConfig.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RootParallelGuiCintLN_type_info;
extern G__linked_taginfo G__RootParallelGuiCintLN_TClass;
extern G__linked_taginfo G__RootParallelGuiCintLN_TBuffer;
extern G__linked_taginfo G__RootParallelGuiCintLN_TMemberInspector;
extern G__linked_taginfo G__RootParallelGuiCintLN_TNamed;
extern G__linked_taginfo G__RootParallelGuiCintLN_TVirtualIsAProxy;
extern G__linked_taginfo G__RootParallelGuiCintLN_ROOT;
extern G__linked_taginfo G__RootParallelGuiCintLN_ROOTcLcLTInitBehavior;
extern G__linked_taginfo G__RootParallelGuiCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RootParallelGuiCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootParallelGuiCintLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__RootParallelGuiCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__RootParallelGuiCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RootParallelGuiCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootParallelGuiCintLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__RootParallelGuiCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__RootParallelGuiCintLN_Ui;
extern G__linked_taginfo G__RootParallelGuiCintLN_UicLcLRootParallelGui;
extern G__linked_taginfo G__RootParallelGuiCintLN_QMainWindow;
extern G__linked_taginfo G__RootParallelGuiCintLN_ROOTcLcLParallelGuiConfig;
extern G__linked_taginfo G__RootParallelGuiCintLN_QWidget;
extern G__linked_taginfo G__RootParallelGuiCintLN_QString;
extern G__linked_taginfo G__RootParallelGuiCintLN_ROOTcLcLParallelGuiMpiLauncher;
extern G__linked_taginfo G__RootParallelGuiCintLN_ROOTcLcLParallelGui;
extern G__linked_taginfo G__RootParallelGuiCintLN_QDialog;
extern G__linked_taginfo G__RootParallelGuiCintLN_UicLcLRootParallelGuiConfig;
extern G__linked_taginfo G__RootParallelGuiCintLN_ROOTcLcLParallelGuiMpiConfig;

/* STUB derived class for protected member access */
